version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
    groups:
        eslint:
            patterns:
                - 'eslint*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
        interval: 'weekly'
    target-branch: 'main'
    labels:
        - 'dependencies'
